/**:
  ros__parameters:
    mujoco_plugins:
      mujoco_camera_plugin:
        type: "mujoco_ros2_control_plugins/CameraPlugin"
        camera_publish_rate: 6.0
        panel_camera:
          policy: streaming
          frame_name: panel_camera_frame
          info_topic: /camera/panel/camera_info
          image_topic: /camera/panel/image_raw
          depth_topic: /camera/panel/depth_raw
      fixture_lamp:
        type: "entryplug_fixture_lamp/FixtureLamp"
