/**:
  ros__parameters:
    mujoco_plugins:
      mujoco_camera_plugin:
        type: "mujoco_ros2_control_plugins/CameraPlugin"
        camera_publish_rate: 6.0
        camera:
          policy: streaming
          frame_name: camera_color_mujoco_frame
          info_topic: /camera/color/camera_info
          image_topic: /camera/color/image_raw
          depth_topic: /camera/aligned_depth_to_color/image_raw
        mirror_camera:
          policy: streaming
          frame_name: mirror_camera_color_mujoco_frame
          info_topic: /camera/mirror/camera_info
          image_topic: /camera/mirror/image_raw
          depth_topic: /camera/mirror/depth_raw
        spectator_camera:
          policy: streaming
          frame_name: spectator_camera_mujoco_frame
          info_topic: /camera/spectator/camera_info
          image_topic: /camera/spectator/image_raw
          depth_topic: /camera/spectator/depth_raw
